version: '3'
services:
  nginx_server:
    image: ttom921/nginx:v1.21.1_with_stream
    container_name: nginx01
    ports:
      # web
      - "80:80"
      - "443:443"
      - "8080:8080"
      # liveview
      - "1935:1935"
      # ftp
      - "2201:2201"
      - "2202:2202"
      # kafka
      - "2181:2181"
      - "9097:9097"
      - "9098:9098"
      - "9099:9099"
    volumes:
      # ---------------- nginx  ----------------
      - ./docker_config/nginx.conf:/etc/nginx/nginx.conf
      # -----------------html ------------------
      - /usr/local/nginx/html:/usr/local/nginx/html
      # -----------------log -------------------
      - /tmp:/var/log/nginx
    
