version: '3.7'
services:
  redis:
    image: redis:alpine
    #restart: "no"
    restart: always
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /data/docker/redis/data:/data
      - ./docker_config/redis.conf:/usr/local/etc/redis/redis.conf
      #--------log----------------------------
      - /tmp/redis-server.log:/usr/local/etc/redis/logs/redis-server.log
    command: redis-server /usr/local/etc/redis/redis.conf --save 60 1
