version: '3.7'
services:
  proxy_webng:
    image: ttom921/nginx:v1.20.1_with_stream
    container_name: proxy_webng
    ports:
      # web
      - "80:80"
      #- "88:88"
      #- "443:443"

    volumes:
      # ---------------- nginx  ----------------
      #- ./docker_config/nginx.conf:/etc/nginx/nginx.conf
      - type: bind
        source: ./docker_config/nginx.conf
        target: /etc/nginx/nginx.conf
      # -----------------html ------------------
      #- /usr/local/nginx/html:/usr/local/nginx/html
      # -----------------log -------------------
      - /tmp:/var/log/nginx
