version: '3.7'
services:
  proxy_ng:
    image: ttom921/nginx:v1.20.1_with_stream
    container_name: proxy_ng
    ports:
      # 1935端口對應的是rtmp服務
      # 1985對應的是http api服務
      # 8080對應的是http-flv、hls的服務器端口
      # liveview
      - "1935:1935"
      - "8080:8080"
      # liveview webrtc
      - "1985:1985"
      - "8000:8000/udp" 
      # ftp
      - "2201:2201"
      - "2202:2202"
      # kafka
      - "2181:2181"
      - "9097:9097"
      - "9098:9098"
      - "9099:9099"
      # elasticsearch
      - "9200:9200"
      - "9300:9300"
      # syslog
      - "514:514"
      - "514:514/udp"
     # redis
      - "6379:6379"
      # postgreSQL
      - "5432:5432"
      # rabbitmq
      - "5673:5673"
    volumes:
      # ---------------- nginx  ----------------
      #- ./docker_config/nginx.conf:/etc/nginx/nginx.conf
      - type: bind
        source: ./docker_config/nginx.conf
        target: /etc/nginx/nginx.conf
      # -----------------html ------------------
      - /usr/local/nginx/html:/usr/local/nginx/html
      # -----------------log -------------------
      - /tmp:/var/log/nginx
    
    
