version: '3.7'
services:
  webfms2:
    image: webfms:python3.9
    #restart: "no"
    restart: always
    hostname: ${WEB_TAG}
    container_name: ${WEB_TAG}
    ports:
      - "${PORT}:80"
      - "${SSLPORT}:443"
    volumes:
      # ---------------- code  ----------------
      - ~/server.viewtec/code:/app
      - /media/vdisk:/media/vdisk
      # ---------------- supervisord ----------------
      - ./docker_config/supervisord-uwsgi-kafka.conf:/etc/supervisor/conf.d/supervisord.conf
      # ---------------- nginx  ----------------
      #- ~/docker/uwsgi/docker_config/nginx.conf:/etc/nginx/nginx.conf 在app的目錄下
      - ./docker_config/nginx.conf:/app/nginx.conf
      - ./docker_config/server.conf:/etc/nginx/server.conf
      - ./docker_config/location_v0.5.conf:/etc/nginx/location_v0.5.conf
      # ---------------- wusgi  ----------------
      # ./docker_config/uwsgi.ini:/app/uwsgi.ini
      - ./docker_config/uwsgi.ini:/etc/uwsgi/uwsgi.ini
      # ---------------- ssl  ----------------
      - /etc/letsencrypt/live/nvtfms.com/fullchain.pem:/etc/nginx/fullchain.pem
      - /etc/letsencrypt/live/nvtfms.com/privkey.pem:/etc/nginx/privkey.pem
      # -----------------html ------------------
      - /usr/share/nginx:/usr/share/nginx
      # -----------------symbolic link ---------------------
      # sudo ln -s /media/vdisk/events /usr/share/nginx/html/events
      # sudo ln -s /media/vdisk/fws /usr/share/nginx/html/fws
      - /usr/share/nginx/html/events:/usr/share/nginx/html/events
      - /usr/share/nginx/html/fws:/usr/share/nginx/html/fws
      - /usr/share/nginx/html/event/images:/usr/share/nginx/html/event/images
      # -----------------log -------------------
      #- /tmp:/var/log/nginx
      #- /tmp:/var/log/supervisor
      #- /tmp:/tmp
      
      - type: bind
        source: /tmp/access_${WEB_TAG}.log
        target: /var/log/nginx/access.log

      - type: bind
        source: /tmp/error_${WEB_TAG}.log
        target: /var/log/nginx/error.log
        
      - type: bind
        source: /tmp/uwsgi_0.5_${WEB_TAG}.log
        target: /tmp/uwsgi_0.5.log

      - type: bind
        source: /tmp/supervisord_${WEB_TAG}.log
        target: /var/log/supervisor/supervisord.log

      - type: bind
        source: /tmp/kafka_service_${WEB_TAG}.log
        target: /tmp/kafka_service.log
    
        
    #ulimits:
    #  nofile:
    #    soft: 98304
    #    hard: 98304
